#!/usr/bin/env python3
"""Generate a small, replayable JDORFX command stream."""

import sys


commands = [
    "newimage 500 350",
    'wintitle "JDORFX commands generated by Python"',
    "color LIGHTBLUE",
    "moveto 40 40",
    "fillrect 180 100",
    "color DARKBLUE",
    "moveto 40 40",
    "drawrect 180 100",
    "color ORANGERED",
    "moveto 280 70",
    "filloval 120 120",
    "color BLACK",
    "moveto 40 220",
    "drawline 430 220",
    "winshow"
]


def main() -> int:
    try:
        for command in commands:
            print(command)
        print(f"Generated {len(commands)} JDORFX commands.", file=sys.stderr)
        return 0
    except BrokenPipeError:
        # The consumer closed the pipe early; do not print a traceback to stdout.
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
